"""
demo_sandbox.py -- live demo of sandbox tools behaviour.

Architecture note:
  The container mounts ONLY _sandbox/ as /workspace inside Docker.
  The model cannot see the broader project tree via bash -- that is intentional isolation.
  Part 1 uses the workspace Python API (read/ls/grep on host FS, routed through presenters).
  Part 2 uses bash inside the container -- showing what the model does in its scratch space.

Run from Tools/mcp-sandbox/:
  python demo_sandbox.py
"""

from __future__ import annotations

import json
import os
import sys
import textwrap
import time

# Force UTF-8 output on Windows
if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from sandbox.api import handle_tool  # noqa: E402

# ── Helpers ──────────────────────────────────────────────────────────

DIVIDER = "=" * 72
SECTION  = "-" * 72
LOG_LINES: list[str] = []


def log(text: str = "") -> None:
    print(text)
    LOG_LINES.append(text)


def banner(title: str) -> None:
    log()
    log(DIVIDER)
    log(f"  {title}")
    log(DIVIDER)


def step(label: str) -> None:
    log()
    log(SECTION)
    log(f"  >> {label}")
    log(SECTION)


def run(tool: str, **kwargs) -> dict:
    """Call handle_tool and pretty-print the result."""
    t0 = time.perf_counter()
    result = handle_tool(tool, kwargs)
    elapsed = (time.perf_counter() - t0) * 1000

    log(f"[tool={tool}  elapsed={elapsed:.0f}ms]")

    if "stdout" in result:
        stdout = result["stdout"] or "(empty)"
        log(textwrap.indent(stdout, "  | "))
        if result.get("stderr"):
            log(f"  STDERR: {result['stderr'][:300]}")
        log(f"  exit_code={result.get('exit_code', '?')}")
    else:
        log(json.dumps(result, ensure_ascii=False, indent=2))

    return result


# ── Part 1: repo analysis via workspace API ───────────────────────────
#
# The model uses workspace tools (ls, read, grep) which operate on the
# HOST filesystem, routed through presenters. This is how it explores
# code BEFORE deciding what to run in the container.

banner("PART 1 -- Repo analysis via workspace API (host FS, structured output)")

step("ls: top-level sandbox package")
run("bash", command="ls Tools/mcp-sandbox/src/sandbox")

step("ls: list with sizes")
run("bash", command="ls -lh Tools/mcp-sandbox/src/sandbox")

step("cat config.py via bash router (medium file, shows structured read)")
run("bash", command="cat Tools/mcp-sandbox/src/sandbox/config.py")

step("grep 'def present' in presenters.py -- flat result (under threshold)")
run("bash", command="grep -n 'def present' Tools/mcp-sandbox/src/sandbox/presenters.py")

step("grep 'def ' across whole sandbox package -- large set, clustered output")
run("bash", command="grep -rn 'def ' Tools/mcp-sandbox/src/sandbox/")

step("find all .py files in sandbox package")
run("bash", command="find Tools/mcp-sandbox/src/sandbox -name '*.py'")

step("head -n 20 api.py -- structured head preview")
run("bash", command="head -n 20 Tools/mcp-sandbox/src/sandbox/api.py")

step("cat presenters.py -- large file (>200 lines), auto file_map kicks in")
run("bash", command="cat Tools/mcp-sandbox/src/sandbox/presenters.py")

step("wc -l on all .py -- real bash passthrough, no routing")
run("bash", command="wc -l Tools/mcp-sandbox/src/sandbox/*.py")


# ── Part 2: _sandbox container workspace ─────────────────────────────
#
# /workspace inside the container == _sandbox/ on host.
# The model writes scripts here, runs them, installs packages, etc.
# This is its personal scratch space -- isolated from the project.

banner("PART 2 -- _sandbox: model's container scratch space")

step("write: create a Python analysis script")
run("write", path="analysis.py", content=textwrap.dedent("""\
    # Auto-generated by sandbox demo
    import os

    def count_python_files(root):
        count = 0
        for dirpath, _, filenames in os.walk(root):
            count += sum(1 for f in filenames if f.endswith('.py'))
        return count

    def largest_file(root):
        largest = ('', 0)
        for dirpath, _, filenames in os.walk(root):
            for f in filenames:
                fp = os.path.join(dirpath, f)
                try:
                    sz = os.path.getsize(fp)
                    if sz > largest[1]:
                        largest = (fp, sz)
                except OSError:
                    pass
        return largest

    if __name__ == '__main__':
        root = '/workspace'
        n = count_python_files(root)
        path, sz = largest_file(root)
        print(f'Python files in /workspace: {n}')
        print(f'Largest file: {path} ({sz} bytes)')
"""))

step("bash: run the script inside container")
run("bash", command="python analysis.py", cwd="_sandbox", timeout_s=30)

step("write: markdown notes file")
run("write", path="notes.md", content=textwrap.dedent("""\
    # Sandbox exploration notes

    ## Key findings
    - /workspace in container == _sandbox/ on host
    - model has full root access inside container
    - project tree is NOT mounted -- isolation is intentional

    ## Next steps
    - [ ] Check session_state.py for loop detection
    - [ ] Review intent.py classification
"""))

step("bash: ls -la inside container -- shows _sandbox contents")
run("bash", command="ls -la /workspace", cwd="_sandbox")

step("bash: install httpx on-the-fly (shows root + network access)")
run("bash",
    command="pip install --quiet httpx && python -c \"import httpx; print('httpx', httpx.__version__)\"",
    cwd="_sandbox",
    timeout_s=120)

step("bash: system info -- uname, df, free")
run("bash", command="uname -a && df -h /workspace && free -m", cwd="_sandbox")

step("bash: git init + commit inside sandbox (shows git works)")
run("bash",
    command=(
        "git init -q && "
        "git config user.email 'sandbox@demo' && "
        "git config user.name 'Sandbox' && "
        "git add . && "
        "git commit -q -m 'initial demo commit' && "
        "git log --oneline"
    ),
    cwd="_sandbox",
    timeout_s=30)

step("bash: show final state of /workspace")
run("bash", command="find /workspace -type f | sort", cwd="_sandbox")


# ── Save log ──────────────────────────────────────────────────────────

banner("DONE")

log_path = os.path.normpath(os.path.join(
    os.path.dirname(__file__), "..", "..", "_sandbox", "demo_run.log"
))

with open(log_path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(LOG_LINES))

log(f"Log written to: {log_path}")
