"""
Settings/settings.py — ASLM-Chat settings manager.

Reads and writes Settings/settings.json, which is generated by first_run.py
and excluded from version control.

Schema of settings.json:
{
    "ui-port": 30000,
    "api-port": 30001,
    "debug": false,
    "secret_key": "<auto-generated>",
    "allowed_hosts": ["127.0.0.1", "localhost"],
    "ollama-service_port": 30002
}
"""

import json
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SETTINGS_FILE = BASE_DIR / 'Settings' / 'settings.json'

# Default values used when a key is missing from settings.json
DEFAULTS: dict = {
    'ui-port': 30000,
    'api-port': 30001,
    'debug': True,
    'secret_key': '',
    'allowed_hosts': ['127.0.0.1', 'localhost'],
    'ollama-service_port': 30002,
    'ollama-service': False,
    'ollama-service_path': None,
    'ollama-service_data': None,
}


def load_settings() -> dict:
    """
    Load settings from settings.json and override with ASLM environment variables.
    Returns a dict merged with DEFAULTS so all keys are always present.
    """
    settings = dict(DEFAULTS)

    if SETTINGS_FILE.exists():
        try:
            with open(SETTINGS_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                settings.update(data)
        except (json.JSONDecodeError, OSError) as e:
            print(f"[ASLM-Chat] Warning: could not read settings.json: {e}")

    # Universal Override with Environment Variables injected by ASLM ModuleRunner
    # Converts ASLM_MY_SETTING to 'my_setting'
    for key, value in os.environ.items():
        if key.startswith('ASLM_') and key not in ('ASLM_MODULE_ID', 'ASLM_MODULE_DIR'):
            setting_key = key[5:].lower()
            
            # Try to parse numeric or boolean strings
            if value.lower() == 'true':
                settings[setting_key] = True
            elif value.lower() == 'false':
                settings[setting_key] = False
            else:
                try:
                    settings[setting_key] = int(value)
                except ValueError:
                    settings[setting_key] = value

    return settings


def save_settings(data: dict) -> None:
    """
    Persist the given settings dict to settings.json.
    Creates the Settings/ directory if it does not exist.
    """
    SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(SETTINGS_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)


def get(key: str, default=None):
    """Return a single setting value by key."""
    return load_settings().get(key, default)


def set(key: str, value) -> None:
    """Update a single setting value and save."""
    data = load_settings()
    data[key] = value
    save_settings(data)
