# Generated by Django 5.2.8 on 2026-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='extracted_text_ready',
            field=models.BooleanField(default=False),
        ),
    ]
