# Generated by Django 5.2.8 on 2026-03-18 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=50),
        ),
        migrations.CreateModel(
            name='OllamaPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_name', '-is_active', '-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('model_name', 'name'), name='unique_ollama_preset_name_per_model')],
            },
        ),
    ]
