# Generated by Django 6.0.2 on 2026-06-20 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_messageattachment_extracted_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleGenAiPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_name', '-is_active', '-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('model_name', 'name'), name='unique_google_genai_preset_name_per_model')],
            },
        ),
        migrations.CreateModel(
            name='OpenAiPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint_url', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=120)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['endpoint_url', 'model_name', '-is_active', '-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('endpoint_url', 'model_name', 'name'), name='unique_openai_preset_name_per_endpoint_model')],
            },
        ),
    ]
