# Generated by Codex for MCP server support.

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_alter_message_role_ollamapreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('transport', models.CharField(choices=[('stdio', 'STDIO'), ('streamable_http', 'Streamable HTTP')], default='stdio', max_length=32)),
                ('command', models.CharField(blank=True, max_length=255)),
                ('args', models.JSONField(blank=True, default=list)),
                ('env', models.JSONField(blank=True, default=dict)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('tool_name_prefix', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ChatMcpServerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_bindings', to='Data.chat')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bindings', to='Data.mcpserverconfig')),
            ],
            options={'ordering': ['chat_id', 'server__name']},
        ),
        migrations.AddConstraint(
            model_name='chatmcpserverbinding',
            constraint=models.UniqueConstraint(fields=('chat', 'server'), name='unique_mcp_server_binding_per_chat'),
        ),
    ]
