# Generated by Django 6.0.2 on 2026-08-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0003_googlegenaipreset_openaipreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachment",
            name="kind",
            field=models.CharField(
                choices=[("image", "Image"), ("file", "File"), ("url", "URL")],
                default="file",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ChatBranch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_branch",
                        to="Data.chat",
                    ),
                ),
                (
                    "child_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_branch_markers",
                        to="Data.message",
                    ),
                ),
                (
                    "source_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_branches",
                        to="Data.chat",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_branches",
                        to="Data.message",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
    ]
