# Generated by Django 5.2.8 on 2026-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_mcp_server_config_chatmcpserverbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active_tool_slug',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='ChatMcpServerBinding',
        ),
        migrations.DeleteModel(
            name='McpServerConfig',
        ),
    ]
