# Generated by Django 5.2.8 on 2026-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_chat_active_tool_slug_delete_chatmcpserverbinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='llm_transcript',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
